// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCekHRFhd2Bt0AqURVA8J4Sq1YwnSqg59w',
    appId: '1:1051945275338:web:215212541bff78c74ac933',
    messagingSenderId: '1051945275338',
    projectId: 'expressive-writing-aab23',
    authDomain: 'expressive-writing-aab23.firebaseapp.com',
    storageBucket: 'expressive-writing-aab23.appspot.com',
    measurementId: 'G-M6TWV36WYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGvgNUeP9RW8HXGlJHkAAkCR9tTLXvcYU',
    appId: '1:1051945275338:android:0a2104bd2331bdf64ac933',
    messagingSenderId: '1051945275338',
    projectId: 'expressive-writing-aab23',
    storageBucket: 'expressive-writing-aab23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq3XFJBTTnwYZCoJWspg6JQG4IRcoJ2Cc',
    appId: '1:1051945275338:ios:4d77da097cc943cc4ac933',
    messagingSenderId: '1051945275338',
    projectId: 'expressive-writing-aab23',
    storageBucket: 'expressive-writing-aab23.appspot.com',
    iosClientId: '1051945275338-2gincrd2lo3ot2rn323ivrbbkoe4bpos.apps.googleusercontent.com',
    iosBundleId: 'com.Ta23ka98.expressivewriting',
  );
}
